# See detailed configuration settings : https://www.pomerium.com/docs/reference/


# this is the domain the identity provider will callback after a user authenticates
authenticate_service_url: https://authenticate.localhost.pomerium.io

####################################################################################
# Certificate settings:  https://www.pomerium.com/docs/reference/certificates.html #
# The example below assumes a certificate and key file will be mounted to a volume #
# available to the  Docker image.                                                  #
####################################################################################
certificate_file: /pomerium/cert.pem
certificate_key_file: /pomerium/privkey.pem

##################################################################################
# Identity provider settings : https://www.pomerium.com/docs/identity-providers/ #
# The keys required in this section vary depending on your IdP. See the          #
# appropriate docs for your IdP to configure Pomerium accordingly.               #
##################################################################################
idp_provider: google
# Google client_id, client_secret: https://www.pomerium.com/docs/identity-providers/google
idp_client_id: GOOGLE_CLIENT_ID
idp_client_secret: GOOGLE_CLIENT_SECRET
jwt_claims_headers: email,groups,user,permissions,nickname

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
cookie_secret: V2JBZk0zWGtsL29UcFUvWjVDWWQ2UHExNXJ0b2VhcDI=
cookie_domain: .localhost.pomerium.io
cookie_name: __local_carparking_one

# https://pomerium.com/reference/#routes
routes:
  - from: https://api.localhost.pomerium.io
    to: http://192.168.50.166:5001 # Ip address local
    allowed_domains:
      - azoom.jp
    pass_identity_headers: true
  - from: https://fe.localhost.pomerium.io
    to: http://192.168.50.166:3001 # Ip address local
    allowed_domains:
      - azoom.jp
    pass_identity_headers: true
  
